=== OceanYan/Platform/Platform.Launcher/Config/Menu.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:attribute name="id" type="xs:string"/>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="code" type="xs:string"/>
  <xs:attribute name="action" type="xs:string"/>
  <xs:attribute name="desc" type="xs:string"/>
  <xs:attribute name="isvisible" type="xs:boolean" default="true"/>
  <xs:attribute name="key" type="xs:string"/>
  <xs:attribute name="value" type="xs:string"/>

  <xs:attributeGroup name="base">
    <xs:attribute ref="id" />
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="desc"/>
    <xs:attribute ref="isvisible"  />
  </xs:attributeGroup>

  <xs:complexType name="menutype">
    <xs:choice maxOccurs="unbounded" minOccurs="1">
      <xs:element name="category" type="categorytype"/>
      <xs:element name="trade" type="tradetype"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="categorytype">
    <xs:choice maxOccurs="unbounded" minOccurs="1">
      <xs:element name="category" type="categorytype"/>
      <xs:element name="trade" type="tradetype"/>
    </xs:choice>
    <xs:attributeGroup ref="base"/>
  </xs:complexType>

  <xs:complexType name="tradetype">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="metadata" type="metadatatype"/>
    </xs:choice>
    <xs:attributeGroup ref="base"/>
    <xs:attribute ref="code" use="required"/>
    <xs:attribute ref="action" use="required"/>
  </xs:complexType>

  <xs:complexType name="metadatatype">
    <xs:attribute ref="key" use="required"/>
    <xs:attribute ref="value" use="required"/>
  </xs:complexType>

  <xs:element name="menu" type="menutype"/>
</xs:schema>

=== OceanYan/Platform/Platform.Launcher/Config/Menu.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Menu.xsd">
  <category  name="客户业务"  >
    <category  name="客户管理" >
      <trade name="客户建立/维护"  code="010101" action="Trade.Customer.T010101" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
      <trade  name="客户建立/维护1" code="010102" action="Trade.Customer.T010102" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
    </category>
    <category  name="客户管理1" >
      <trade  name="客户建立/维护" code="020101" action="Trade.Customer.T010101" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
      <trade  name="客户建立/维护1" code="020102" action="Trade.Customer.T010102" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
    </category>
  </category>
  <category  name="客户业务1" >
    <category  name="客户管理11" >
      <trade  name="客户建立/维护111" code="030101" action="Trade.Customer.T010101" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
      <trade  name="客户建立/维护21" code="030102" action="Trade.Customer.T010102" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
    </category>
    <category  name="客户管理31" >
      <trade  name="客户建立/维护" code="040101" action="Trade.Customer.T010101" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
      <trade  name="客户建立/维护41" code="040102" action="Trade.Customer.T010102" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
      <trade  name="客户建立/维护" code="0140101" action="Trade.Customer.T010101" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
      <trade  name="客户建立/维护41" code="0240102" action="Trade.Customer.T010102" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
      <trade  name="客户建立/维护" code="0340101" action="Trade.Customer.T010101" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
      <trade  name="客户建立/维护41asdasda大大苏打大苏打啊实打实打算" code="0440102" action="Trade.Customer.T010102" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
      <trade  name="客户建立/维护" code="0450101" action="Trade.Customer.T010101" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
      <trade  name="客户建立/维护41" code="0460102" action="Trade.Customer.T010102" >
        <metadata value="true" key="isPrintNumber"/>
        <metadata value="true" key="isAuth"/>
        <metadata value="1100" key="Priority"/>
      </trade>
    </category>
  </category>
</menu>
